import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, existsSync, readFileSync, rmSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { migrateCommand } from '../commands/migrate.js'
import { SHEEPDOG_DIR } from '../../constants.js'

let tmpDir: string

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'sheepdog-migrate-'))
})

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true })
})

function createTaskYaml(taskDir: string, content: string) {
  mkdirSync(taskDir, { recursive: true })
  writeFileSync(join(taskDir, 'task.yaml'), content, 'utf-8')
}

describe('migrateCommand', () => {
  it('generates main.ts for a simple task', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'simple-task')
    createTaskYaml(taskDir, `name: "simple-task"
phases:
  - description: "Phase 1"
onPhaseFailure: stop
`)

    await migrateCommand({ task: 'simple-task', dir: tmpDir })

    const mainTs = join(taskDir, 'main.ts')
    expect(existsSync(mainTs)).toBe(true)

    const content = readFileSync(mainTs, 'utf-8')
    expect(content).toContain('// Generated by sheepdog migrate')
    expect(content).toContain("import { runAgentStep, run_command, checkpoint } from '@sheepdog/sandbox'")
    expect(content).toContain('await checkpoint("phase-1")')
    expect(content).toContain("agent: 'opencode'")
    expect(content).toContain('plan: "./todo-phase-1.md"')
    expect(content).toContain('on_verification_fail: "stop"')
  })

  it('includes runBeforeAll and runAfterAll commands', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'full-task')
    createTaskYaml(taskDir, `name: "full-task"
phases:
  - description: "Phase 1"
runBeforeAll:
  - npm install
  - npm run build
runAfterAll:
  - npm run test
onPhaseFailure: stop
`)

    await migrateCommand({ task: 'full-task', dir: tmpDir })

    const content = readFileSync(join(taskDir, 'main.ts'), 'utf-8')
    expect(content).toContain('// runBeforeAll commands')
    expect(content).toContain("await run_command({ command: \"npm install\" })")
    expect(content).toContain("await run_command({ command: \"npm run build\" })")
    expect(content).toContain('// runAfterAll commands')
    expect(content).toContain("await run_command({ command: \"npm run test\" })")
  })

  it('maps onPhaseFailure correctly', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'fail-task')
    createTaskYaml(taskDir, `name: "fail-task"
phases:
  - description: "Phase 1"
onPhaseFailure: continue
`)

    await migrateCommand({ task: 'fail-task', dir: tmpDir })

    const content = readFileSync(join(taskDir, 'main.ts'), 'utf-8')
    expect(content).toContain('on_verification_fail: "continue"')
  })

  it('includes runAfter on phases as run_command calls', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'runafter-task')
    createTaskYaml(taskDir, `name: "runafter-task"
phases:
  - description: "Phase 1"
    runAfter:
      - npm run typecheck
      - npm run lint
  - description: "Phase 2"
onPhaseFailure: stop
`)

    await migrateCommand({ task: 'runafter-task', dir: tmpDir })

    const content = readFileSync(join(taskDir, 'main.ts'), 'utf-8')
    expect(content).toContain('// phase-1 runAfter commands')
    expect(content).toContain("await run_command({ command: \"npm run typecheck\" })")
    expect(content).toContain("await run_command({ command: \"npm run lint\" })")
    expect(content).toContain('await checkpoint("phase-2")')
  })

  it('does not delete original task.yaml', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'preserve-task')
    createTaskYaml(taskDir, `name: "preserve-task"
phases:
  - description: "Phase 1"
onPhaseFailure: stop
`)

    await migrateCommand({ task: 'preserve-task', dir: tmpDir })

    expect(existsSync(join(taskDir, 'task.yaml'))).toBe(true)
  })

  it('warns and skips when main.ts already exists without --force', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'existing-task')
    createTaskYaml(taskDir, `name: "existing-task"
phases:
  - description: "Phase 1"
onPhaseFailure: stop
`)
    writeFileSync(join(taskDir, 'main.ts'), 'original content', 'utf-8')

    await migrateCommand({ task: 'existing-task', dir: tmpDir })

    const content = readFileSync(join(taskDir, 'main.ts'), 'utf-8')
    expect(content).toBe('original content')
  })

  it('overwrites main.ts when --force is used', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'force-task')
    createTaskYaml(taskDir, `name: "force-task"
phases:
  - description: "Phase 1"
onPhaseFailure: stop
`)
    writeFileSync(join(taskDir, 'main.ts'), 'original content', 'utf-8')

    await migrateCommand({ task: 'force-task', dir: tmpDir, force: true })

    const content = readFileSync(join(taskDir, 'main.ts'), 'utf-8')
    expect(content).toContain('// Generated by sheepdog migrate')
    expect(content).not.toBe('original content')
  })

  it('generates expected output for a complex task', async () => {
    const taskDir = join(tmpDir, SHEEPDOG_DIR, 'complex-task')
    createTaskYaml(taskDir, `name: "complex-task"
phases:
  - description: "Setup and Planning"
  - description: "Implementation"
    runAfter:
      - npm run typecheck
  - description: "Testing"
    runAfter:
      - npm test
runBeforeAll:
  - npm install
runAfterAll:
  - npm run typecheck
  - npm test
onPhaseFailure: attempt fix
`)

    await migrateCommand({ task: 'complex-task', dir: tmpDir })

    const content = readFileSync(join(taskDir, 'main.ts'), 'utf-8')

    const expected = `// Generated by sheepdog migrate — converts an existing YAML task to the script format

import { runAgentStep, run_command, checkpoint } from '@sheepdog/sandbox'

// runBeforeAll commands
await run_command({ command: "npm install" })

// Phase 1: Setup and Planning
await checkpoint("phase-1")
await runAgentStep({
  agent: 'opencode',
  plan: "./todo-phase-1.md",
  on_verification_fail: "attempt fix",
})

// Phase 2: Implementation
await checkpoint("phase-2")
await runAgentStep({
  agent: 'opencode',
  plan: "./todo-phase-2.md",
  on_verification_fail: "attempt fix",
})
// phase-2 runAfter commands
await run_command({ command: "npm run typecheck" })

// Phase 3: Testing
await checkpoint("phase-3")
await runAgentStep({
  agent: 'opencode',
  plan: "./todo-phase-3.md",
  on_verification_fail: "attempt fix",
})
// phase-3 runAfter commands
await run_command({ command: "npm test" })

// runAfterAll commands
await run_command({ command: "npm run typecheck" })
await run_command({ command: "npm test" })
`

    expect(content).toBe(expected)
  })
})
