import { resolve, join, relative } from 'node:path'
import { writeFileSync, existsSync } from 'node:fs'
import { loadTask } from '../../task/task-loader.js'
import { info, success, warn, step } from '../../utils/logger.js'
import { SHEEPDOG_DIR } from '../../constants.js'
import type { Task } from '../../types/types.js'

export interface MigrateOptions {
  task: string
  dir: string
  force?: boolean
}

function generateMainScript(task: Task): string {
  const lines: string[] = []

  lines.push('// Generated by sheepdog migrate — converts an existing YAML task to the script format')
  lines.push('')
  lines.push("import { runAgentStep, run_command, checkpoint } from '@sheepdog/sandbox'")
  lines.push('')

  if (task.runBeforeAll.length > 0) {
    lines.push('// runBeforeAll commands')
    for (const cmd of task.runBeforeAll) {
      lines.push(`await run_command({ command: ${JSON.stringify(cmd.command)} })`)
    }
    lines.push('')
  }

  for (let i = 0; i < task.phases.length; i++) {
    const phase = task.phases[i]
    const phaseId = `phase-${i + 1}`

    lines.push(`// Phase ${i + 1}: ${phase.label}`)
    lines.push(`await checkpoint(${JSON.stringify(phaseId)})`)
    lines.push('await runAgentStep({')
    lines.push('  agent: \'opencode\',')
    lines.push(`  plan: ${JSON.stringify(`./todo-phase-${i + 1}.md`)},`)
    lines.push(`  on_verification_fail: ${JSON.stringify(task.onPhaseFailure)},`)
    lines.push('})')

    if (phase.runAfter.length > 0) {
      lines.push(`// ${phaseId} runAfter commands`)
      for (const cmd of phase.runAfter) {
        lines.push(`await run_command({ command: ${JSON.stringify(cmd.command)} })`)
      }
    }

    if (i < task.phases.length - 1) {
      lines.push('')
    }
  }

  if (task.runAfterAll.length > 0) {
    lines.push('')
    lines.push('// runAfterAll commands')
    for (const cmd of task.runAfterAll) {
      lines.push(`await run_command({ command: ${JSON.stringify(cmd.command)} })`)
    }
  }

  return lines.join('\n') + '\n'
}

export async function migrateCommand(options: MigrateOptions): Promise<void> {
  const projectRoot = resolve(options.dir)
  const taskName = options.task
  const taskDir = join(projectRoot, SHEEPDOG_DIR, taskName)
  const mainTsPath = join(taskDir, 'main.ts')

  info(`Migrating task '${taskName}' to script format`)

  const loaded = loadTask(taskDir)
  const task = loaded.task

  if (existsSync(mainTsPath)) {
    if (options.force) {
      warn(`Overwriting existing main.ts (--force)`)
    } else {
      warn(`main.ts already exists in ${join(SHEEPDOG_DIR, taskName)}. Use --force to overwrite.`)
      return
    }
  }

  const script = generateMainScript(task)

  writeFileSync(mainTsPath, script, 'utf-8')
  step(`Created ${relative(projectRoot, mainTsPath)}`)

  success(`Task '${taskName}' migrated. ${join(SHEEPDOG_DIR, taskName, 'main.ts')} has been generated.`)
}
