import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { resolve } from 'node:path'
import { mkdirSync } from 'node:fs'
import { info, success, step, error } from '../../utils/logger.js'

const execFileAsync = promisify(execFile)

export interface PlanOptions {
  dir?: string
}

export async function planCommand(description: string, options?: PlanOptions): Promise<void> {
  const projectRoot = resolve(options?.dir ?? process.cwd())
  const name = description
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)

  const taskDir = resolve(projectRoot, 'sheepdog', name)
  mkdirSync(taskDir, { recursive: true })

  info(`Generating plan for: ${description}`)
  step(`Task directory: ${taskDir}`)

  const prompt = `Analyze the project at ${projectRoot} and create a sheepdog task plan.

The description of the work is: "${description}"

Create the following files:

## 1. ${taskDir}/task.yaml

YAML config with 4 phases, test commands, and failure handling.

Example format:
\`\`\`yaml
name: "${name}"
phases:
  - id: phase-1
    file: todo-phase-1.md
    label: "Phase 1: Analysis & Planning"
  - id: phase-2
    file: todo-phase-2.md
    label: "Phase 2: Implementation"
  - id: phase-3
    file: todo-phase-3.md
    label: "Phase 3: Testing & Refinement"
  - id: phase-4
    file: todo-phase-4.md
    label: "Phase 4: Polish"
run_between:
  - command: npm run typecheck
  - command: npm run lint
    optional: true
  - command: npm test
    fail_on_error: true
run_after_all:
  - command: npm run typecheck
  - command: npm test
on_test_failure:
  action: append_to_next_phase
\`\`\`

## 2-5. ${taskDir}/todo-phase-1.md through todo-phase-4.md

Each is a markdown file with detailed instructions for that phase.
Phase instructions should be clear, step-by-step, and specific to the project.
Include specific files to modify, patterns to follow, and acceptance criteria.

IMPORTANT: Write each file using the \`write\` tool. Do not just describe them — create them.`

  try {
    info('Invoking opencode agent to generate plan...')
    const { stdout } = await execFileAsync('opencode', [
      '--prompt', prompt,
      '--yes',
    ], {
      cwd: projectRoot,
      timeout: 600_000,
      maxBuffer: 10 * 1024 * 1024,
    })

    success('Plan generated by agent.')
    console.log(stdout)
  } catch (err: any) {
    error(`Agent exited with error: ${err.message}`)
    info('Check if the task files were created. If not, try running the plan command again.')
    process.exit(1)
  }

  info(`\nRun: sheepdog run ${name}`)
}
